from __future__ import annotations

LOCAL_COMPOUNDS = {
    "ethanol": {
        "aliases": ["etanol", "ethanol", "alcool etilico", "álcool etílico", "64-17-5"],
        "identity": {
            "name": "Etanol",
            "preferred_name": "Ethanol",
            "cas": "64-17-5",
            "formula": "C2H6O",
            "molecular_weight": 46.07,
        },
        "hazards": [
            "H225 — Líquido e vapor altamente inflamáveis",
            "H319 — Provoca irritação ocular grave",
            "H336 — Pode provocar sonolência ou vertigens",
        ],
        "nfpa": {"health": 2, "fire": 3, "reactivity": 0, "special": ""},
        "physchem": {
            "flash_point_c": {"value": 13.0, "unit": "°C", "source": "local_seed"},
            "boiling_point_c": {"value": 78.4, "unit": "°C", "source": "local_seed"},
            "autoignition_c": {"value": 365.0, "unit": "°C", "source": "local_seed"},
            "lfl_volpct": {"value": 3.3, "unit": "%vol", "source": "local_seed"},
            "ufl_volpct": {"value": 19.0, "unit": "%vol", "source": "local_seed"},
            "vapor_pressure_kpa_20c": {"value": 5.8, "unit": "kPa", "source": "local_seed"},
            "density_liquid_g_cm3": {"value": 0.789, "unit": "g/cm3", "source": "local_seed"},
            "vapor_density_air": {"value": 1.59, "unit": "air=1", "source": "local_seed"},
            "mie_mj": {"value": 0.65, "unit": "mJ", "source": "local_seed"},
        },
        "exposure_limits": {
            "IDLH_ppm": {"value": 3300, "unit": "ppm", "source": "local_seed"},
            "TLV_TWA_ppm": {"value": 1000, "unit": "ppm", "source": "local_seed"},
        },
        "reactivity": {
            "corrosive": False,
            "pressurized": False,
            "reactive_hazard": False,
            "incompatibilities": ["oxidantes fortes", "fontes de ignição", "superfícies quentes"],
            "notes": ["Priorizar inflamabilidade, ventilação e controle de ignição."],
        },
    },
    "acetone": {
        "aliases": ["acetona", "acetone", "67-64-1", "propanona"],
        "identity": {
            "name": "Acetona",
            "preferred_name": "Acetone",
            "cas": "67-64-1",
            "formula": "C3H6O",
            "molecular_weight": 58.08,
        },
        "hazards": [
            "H225 — Líquido e vapor altamente inflamáveis",
            "H319 — Provoca irritação ocular grave",
            "H336 — Pode provocar sonolência ou vertigens",
        ],
        "nfpa": {"health": 1, "fire": 3, "reactivity": 0, "special": ""},
        "physchem": {
            "flash_point_c": {"value": -18.0, "unit": "°C", "source": "local_seed"},
            "boiling_point_c": {"value": 56.1, "unit": "°C", "source": "local_seed"},
            "autoignition_c": {"value": 465.0, "unit": "°C", "source": "local_seed"},
            "lfl_volpct": {"value": 2.5, "unit": "%vol", "source": "local_seed"},
            "ufl_volpct": {"value": 12.8, "unit": "%vol", "source": "local_seed"},
            "vapor_pressure_kpa_20c": {"value": 23.5, "unit": "kPa", "source": "local_seed"},
            "density_liquid_g_cm3": {"value": 0.791, "unit": "g/cm3", "source": "local_seed"},
            "vapor_density_air": {"value": 2.0, "unit": "air=1", "source": "local_seed"},
            "mie_mj": {"value": 1.15, "unit": "mJ", "source": "local_seed"},
        },
        "exposure_limits": {
            "IDLH_ppm": {"value": 2500, "unit": "ppm", "source": "local_seed"},
            "TLV_TWA_ppm": {"value": 500, "unit": "ppm", "source": "local_seed"},
        },
        "reactivity": {
            "corrosive": False,
            "pressurized": False,
            "reactive_hazard": False,
            "incompatibilities": ["oxidantes fortes", "fontes de ignição"],
            "notes": ["Alta volatilidade e atmosfera inflamável são centrais."],
        },
    },
    "sulfuric_acid": {
        "aliases": ["ácido sulfúrico", "acido sulfurico", "sulfuric acid", "7664-93-9"],
        "identity": {
            "name": "Ácido Sulfúrico",
            "preferred_name": "Sulfuric acid",
            "cas": "7664-93-9",
            "formula": "H2SO4",
            "molecular_weight": 98.08,
        },
        "hazards": [
            "H314 — Provoca queimaduras graves à pele e danos aos olhos",
            "H290 — Pode ser corrosivo para metais",
        ],
        "nfpa": {"health": 3, "fire": 0, "reactivity": 2, "special": "W"},
        "physchem": {
            "boiling_point_c": {"value": 337.0, "unit": "°C", "source": "local_seed"},
            "melting_point_c": {"value": 10.0, "unit": "°C", "source": "local_seed"},
            "density_liquid_g_cm3": {"value": 1.84, "unit": "g/cm3", "source": "local_seed"},
            "vapor_pressure_kpa_20c": {"value": 0.001, "unit": "kPa", "source": "local_seed"},
        },
        "exposure_limits": {
            "IDLH_mg_m3": {"value": 15.0, "unit": "mg/m3", "source": "local_seed"},
            "TLV_STEL_mg_m3": {"value": 0.2, "unit": "mg/m3", "source": "local_seed"},
        },
        "reactivity": {
            "corrosive": True,
            "pressurized": False,
            "reactive_hazard": True,
            "incompatibilities": ["água (adição inadequada)", "bases fortes", "metais reativos", "orgânicos incompatíveis"],
            "notes": ["Foco em corrosão, materiais de construção e incompatibilidade de mistura."],
        },
    },
    "ammonia": {
        "aliases": ["amônia", "amonia", "ammonia", "7664-41-7", "nh3"],
        "identity": {
            "name": "Amônia",
            "preferred_name": "Ammonia",
            "cas": "7664-41-7",
            "formula": "NH3",
            "molecular_weight": 17.03,
        },
        "hazards": [
            "H221 — Gás inflamável",
            "H314 — Provoca queimaduras graves à pele e danos aos olhos",
            "H331 — Tóxico por inalação",
            "H400 — Muito tóxico para organismos aquáticos",
        ],
        "nfpa": {"health": 3, "fire": 1, "reactivity": 0, "special": ""},
        "physchem": {
            "boiling_point_c": {"value": -33.3, "unit": "°C", "source": "local_seed"},
            "autoignition_c": {"value": 651.0, "unit": "°C", "source": "local_seed"},
            "lfl_volpct": {"value": 15.0, "unit": "%vol", "source": "local_seed"},
            "ufl_volpct": {"value": 28.0, "unit": "%vol", "source": "local_seed"},
            "vapor_density_air": {"value": 0.59, "unit": "air=1", "source": "local_seed"},
            "flash_point_c": {"value": 11.0, "unit": "°C (aq)", "source": "local_seed"},
        },
        "exposure_limits": {
            "IDLH_ppm": {"value": 300, "unit": "ppm", "source": "local_seed"},
            "TLV_TWA_ppm": {"value": 25, "unit": "ppm", "source": "local_seed"},
            "ERPG_2_ppm": {"value": 200, "unit": "ppm", "source": "local_seed"},
            "ERPG_3_ppm": {"value": 1000, "unit": "ppm", "source": "local_seed"},
        },
        "reactivity": {
            "corrosive": True,
            "pressurized": True,
            "reactive_hazard": False,
            "incompatibilities": ["ácidos", "oxidantes fortes", "cobre/ligas incompatíveis em algumas condições"],
            "notes": ["Priorizar toxic release, isolamento, detecção e alívio."],
        },
    },
    "methane": {
        "aliases": ["metano", "methane", "74-82-8", "gás natural", "gas natural"],
        "identity": {
            "name": "Metano",
            "preferred_name": "Methane",
            "cas": "74-82-8",
            "formula": "CH4",
            "molecular_weight": 16.04,
        },
        "hazards": [
            "H220 — Gás extremamente inflamável",
            "H280 — Contém gás sob pressão",
        ],
        "nfpa": {"health": 1, "fire": 4, "reactivity": 0, "special": ""},
        "physchem": {
            "boiling_point_c": {"value": -161.5, "unit": "°C", "source": "local_seed"},
            "autoignition_c": {"value": 537.0, "unit": "°C", "source": "local_seed"},
            "lfl_volpct": {"value": 5.0, "unit": "%vol", "source": "local_seed"},
            "ufl_volpct": {"value": 15.0, "unit": "%vol", "source": "local_seed"},
            "vapor_density_air": {"value": 0.55, "unit": "air=1", "source": "local_seed"},
            "mie_mj": {"value": 0.28, "unit": "mJ", "source": "local_seed"},
        },
        "exposure_limits": {},
        "reactivity": {
            "corrosive": False,
            "pressurized": True,
            "reactive_hazard": False,
            "incompatibilities": ["oxidantes", "fontes de ignição"],
            "notes": ["Priorizar atmosfera inflamável, ventilação, isolamento e ignição."],
        },
    },
    "toluene": {
        "aliases": ["tolueno", "toluene", "108-88-3", "toluol"],
        "identity": {
            "name": "Tolueno",
            "preferred_name": "Toluene",
            "cas": "108-88-3",
            "formula": "C7H8",
            "molecular_weight": 92.14,
        },
        "hazards": [
            "H225 — Líquido e vapor altamente inflamáveis",
            "H304 — Pode ser fatal se ingerido e penetrar nas vias respiratórias",
            "H315 — Provoca irritação cutânea",
            "H336 — Pode provocar sonolência ou vertigens",
        ],
        "nfpa": {"health": 2, "fire": 3, "reactivity": 0, "special": ""},
        "physchem": {
            "flash_point_c": {"value": 4.0, "unit": "°C", "source": "local_seed"},
            "boiling_point_c": {"value": 110.6, "unit": "°C", "source": "local_seed"},
            "autoignition_c": {"value": 480.0, "unit": "°C", "source": "local_seed"},
            "lfl_volpct": {"value": 1.1, "unit": "%vol", "source": "local_seed"},
            "ufl_volpct": {"value": 7.1, "unit": "%vol", "source": "local_seed"},
            "vapor_pressure_kpa_20c": {"value": 2.9, "unit": "kPa", "source": "local_seed"},
            "density_liquid_g_cm3": {"value": 0.867, "unit": "g/cm3", "source": "local_seed"},
            "vapor_density_air": {"value": 3.1, "unit": "air=1", "source": "local_seed"},
            "mie_mj": {"value": 0.24, "unit": "mJ", "source": "local_seed"},
        },
        "exposure_limits": {
            "IDLH_ppm": {"value": 500, "unit": "ppm", "source": "local_seed"},
            "TLV_TWA_ppm": {"value": 20, "unit": "ppm", "source": "local_seed"},
        },
        "reactivity": {
            "corrosive": False,
            "pressurized": False,
            "reactive_hazard": False,
            "incompatibilities": ["oxidantes fortes", "fontes de ignição"],
            "notes": ["Inflamabilidade e exposição por vapores são eixos centrais."],
        },
    },
}
