from __future__ import annotations

ACTION_COLUMN_ALIASES = {
    "action required": "Ação Recomendada",
    "recommended action": "Ação Recomendada",
    "action recommended": "Ação Recomendada",
    "action": "Ação Recomendada",
    "actions": "Ação Recomendada",
    "description": "Ação Recomendada",
    "status": "Status",
    "owner": "Responsável",
    "responsible": "Responsável",
    "due days": "Prazo (Dias)",
    "deadline days": "Prazo (Dias)",
    "due date": "Prazo",
    "deadline": "Prazo",
    "resource": "Recurso",
    "severity": "Criticidade",
    "criticality": "Criticidade",
    "niosh hierarchy": "Hierarquia NIOSH",
    "requires moc?": "Requer MOC?",
    "requires moc": "Requer MOC?",
    "moc required?": "Requer MOC?",
    "moc required": "Requer MOC?",
}

ACTION_VALUE_MAPPINGS = {
    "Status": {
        "pending": "Aberto",
        "open": "Aberto",
        "in progress": "Em Andamento",
        "waiting budget": "Aguardando Verba",
        "budget pending": "Aguardando Verba",
        "closed": "Fechado",
    },
    "Criticidade": {
        "critical": "Crítica",
        "high": "Alta",
        "medium": "Média",
        "moderate": "Média",
        "low": "Baixa",
    },
    "Recurso": {
        "capex": "CAPEX",
        "opex": "OPEX",
    },
    "Responsável": {
        "engineering": "Engenharia",
        "maintenance": "Manutenção",
        "operations": "Operação",
        "operation": "Operação",
        "hse": "HSE",
    },
}

AACE_CLASS5_LIBRARY = [
    {
        "label": "SIS / SIF / ESD",
        "resource": "CAPEX",
        "keywords": ["sis", "sif", "esd", "shutdown", "trip", "intertravamento"],
        "min": 120000.0,
        "p50": 220000.0,
        "max": 450000.0,
    },
    {
        "label": "CLP / PLC / Painel",
        "resource": "CAPEX",
        "keywords": ["clp", "plc", "logic solver", "painel", "ihm", "remota"],
        "min": 45000.0,
        "p50": 90000.0,
        "max": 180000.0,
    },
    {
        "label": "Válvula / SDV / PSV / Atuador",
        "resource": "CAPEX",
        "keywords": ["válvula", "valvula", "psv", "sdv", "atuador", "bloqueio"],
        "min": 18000.0,
        "p50": 42000.0,
        "max": 110000.0,
    },
    {
        "label": "Instrumentação / Alarmes / Sensores",
        "resource": "CAPEX",
        "keywords": ["sensor", "transmissor", "alarme", "detector", "instrument", "pressostato", "chave"],
        "min": 12000.0,
        "p50": 30000.0,
        "max": 70000.0,
    },
    {
        "label": "Treinamento / Procedimento",
        "resource": "OPEX",
        "keywords": ["treinamento", "capacitação", "procedimento", "instrução", "instrucao", "treinar", "reciclagem"],
        "min": 3000.0,
        "p50": 8500.0,
        "max": 18000.0,
    },
    {
        "label": "Estudo / HAZOP / LOPA / Engenharia",
        "resource": "OPEX",
        "keywords": ["estudo", "hazop", "lopa", "análise", "analise", "simulação", "simulacao", "investigação", "investigacao"],
        "min": 7000.0,
        "p50": 15000.0,
        "max": 35000.0,
    },
]
